[project]
name = "gcp-re-execute-workflow"
version = "0.1.0"
description = "PoC by kktae@mz.co.kr"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-cloud-workflows>=1.19.0",
    "python-dotenv>=1.2.1",
]
